# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-argument-parser" = "sha256-90ECc3iEmxvOUk9iLKbQdQEz88dOisPqWsJLOFcKUV8=";
    "swift-subprocess" = "sha256-8Ujur2TwISoXo9LZ2Kev8v0uGx/RZyJqyZ4sNi7Q6/4=";
    "swift-system" = "sha256-bfxm2WS+4qcgSzheWTvRloDAIIIHzPZ8SaAZq9bWmSc=";
  };
}
